### ISSUE TITLE
Delete user through CLI runtime error

### ISSUE THREAD

**Issue by RoboMagus** [go-vikunja/api#23]
I've been toying around with using Oauth2 login on Vikunja, and as a result of that some additional unintended users have been created.
When trying to delete these accounts through CLI (`./vikunja user delete 3 --now`) I get the following output:
```
2022/03/20 15:13:17 Using config file: /app/vikunja/config.yaml
2022-03-20T15:13:17.330165405Z: INFO    ▶ migration/Migrate 048 Ran all migrations successfully.
2022-03-20T15:13:17.330984133Z: INFO    ▶ models/RegisterReminderCron 049 Mailer is disabled, not sending reminders per mail
2022-03-20T15:13:17.331467773Z: INFO    ▶ models/RegisterOverdueReminderCron 04a Mailer is disabled, not sending overdue per mail
You requested to delete the user immediately. Are you sure?
To confirm, please type "yes, I confirm" in all uppercase:
2022-03-20T15:13:17.333698517Z: INFO    ▶ [EVENTS] 04e Adding handler, handler_name=poison.logger, topic=poison
2022-03-20T15:13:17.333989771Z: INFO    ▶ [EVENTS] 050 Adding handler, handler_name=team.member.added.team.member.added.notification, topic=team.member.added
2022-03-20T15:13:17.334122269Z: INFO    ▶ [EVENTS] 051 Adding handler, handler_name=user.export.requested.handle.user.data.export, topic=user.export.requested
2022-03-20T15:13:17.33420049Z: INFO     ▶ [EVENTS] 052 Adding handler, handler_name=namespace.created.namespace.counter.increase, topic=namespace.created
2022-03-20T15:13:17.334244952Z: INFO    ▶ [EVENTS] 053 Adding handler, handler_name=team.created.team.counter.increase, topic=team.created
2022-03-20T15:13:17.334289637Z: INFO    ▶ [EVENTS] 054 Adding handler, handler_name=task.created.task.counter.increase, topic=task.created
2022-03-20T15:13:17.334329507Z: INFO    ▶ [EVENTS] 055 Adding handler, topic=task.created, handler_name=task.created.task.created.mentions
2022-03-20T15:13:17.334365339Z: INFO    ▶ [EVENTS] 056 Adding handler, handler_name=team.deleted.team.counter.decrease, topic=team.deleted
2022-03-20T15:13:17.334401691Z: INFO    ▶ [EVENTS] 057 Adding handler, handler_name=task.assignee.created.task.assigned.notification.send, topic=task.assignee.created
2022-03-20T15:13:17.334445116Z: INFO    ▶ [EVENTS] 058 Adding handler, handler_name=task.assignee.created.task.assignee.subscribe, topic=task.assignee.created
2022-03-20T15:13:17.33448219Z: INFO     ▶ [EVENTS] 059 Adding handler, topic=list.deleted, handler_name=list.deleted.list.counter.decrease
2022-03-20T15:13:17.334546207Z: INFO    ▶ [EVENTS] 05a Adding handler, handler_name=namespace.deleted.namespace.counter.decrease, topic=namespace.deleted
2022-03-20T15:13:17.334645576Z: INFO    ▶ [EVENTS] 05b Adding handler, handler_name=task.updated.task.updated.mentions, topic=task.updated
2022-03-20T15:13:17.334710649Z: INFO    ▶ [EVENTS] 05c Adding handler, handler_name=user.created.increase.user.counter, topic=user.created
2022-03-20T15:13:17.334776889Z: INFO    ▶ [EVENTS] 05d Adding handler, handler_name=list.created.list.counter.increase, topic=list.created
2022-03-20T15:13:17.334838295Z: INFO    ▶ [EVENTS] 05e Adding handler, handler_name=list.created.send.list.created.notification, topic=list.created
2022-03-20T15:13:17.334918942Z: INFO    ▶ [EVENTS] 05f Adding handler, handler_name=task.comment.created.task.comment.notification.send, topic=task.comment.created
2022-03-20T15:13:17.334982663Z: INFO    ▶ [EVENTS] 060 Adding handler, handler_name=task.deleted.task.counter.decrease, topic=task.deleted
2022-03-20T15:13:17.335042422Z: INFO    ▶ [EVENTS] 061 Adding handler, handler_name=task.deleted.task.deleted.notification.send, topic=task.deleted
2022-03-20T15:13:17.335102717Z: INFO    ▶ [EVENTS] 062 Adding handler, topic=task.comment.edited, handler_name=task.comment.edited.handle.task.comment.edit.mentions
2022-03-20T15:13:17.338781215Z: INFO    ▶ [EVENTS] 079 Starting handler, subscriber_name=team.deleted.team.counter.decrease, topic=team.deleted
2022-03-20T15:13:17.338815344Z: INFO    ▶ [EVENTS] 07a Starting handler, subscriber_name=namespace.created.namespace.counter.increase, topic=namespace.created
2022-03-20T15:13:17.339021119Z: INFO    ▶ [EVENTS] 07b Starting handler, subscriber_name=poison.logger, topic=poison
2022-03-20T15:13:17.339120562Z: INFO    ▶ [EVENTS] 07c Starting handler, subscriber_name=namespace.deleted.namespace.counter.decrease, topic=namespace.deleted
2022-03-20T15:13:17.339321892Z: INFO    ▶ [EVENTS] 07e Starting handler, subscriber_name=list.deleted.list.counter.decrease, topic=list.deleted
2022-03-20T15:13:17.339510445Z: INFO    ▶ [EVENTS] 081 Starting handler, subscriber_name=task.comment.edited.handle.task.comment.edit.mentions, topic=task.comment.edited
2022-03-20T15:13:17.339652257Z: INFO    ▶ [EVENTS] 083 Starting handler, subscriber_name=task.comment.created.task.comment.notification.send, topic=task.comment.created
2022-03-20T15:13:17.339708145Z: INFO    ▶ [EVENTS] 084 Starting handler, subscriber_name=user.export.requested.handle.user.data.export, topic=user.export.requested
2022-03-20T15:13:17.339735923Z: INFO    ▶ [EVENTS] 085 Starting handler, subscriber_name=task.created.task.counter.increase, topic=task.created
2022-03-20T15:13:17.339826773Z: INFO    ▶ [EVENTS] 086 Starting handler, subscriber_name=list.created.send.list.created.notification, topic=list.created
2022-03-20T15:13:17.33992092Z: INFO     ▶ [EVENTS] 087 Starting handler, subscriber_name=user.created.increase.user.counter, topic=user.created
2022-03-20T15:13:17.339417409Z: INFO    ▶ [EVENTS] 07f Starting handler, subscriber_name=team.created.team.counter.increase, topic=team.created
2022-03-20T15:13:17.339646202Z: INFO    ▶ [EVENTS] 082 Starting handler, topic=team.member.added, subscriber_name=team.member.added.team.member.added.notification
2022-03-20T15:13:17.340030363Z: INFO    ▶ [EVENTS] 08a Starting handler, subscriber_name=task.assignee.created.task.assigned.notification.send, topic=task.assignee.created
2022-03-20T15:13:17.339927827Z: INFO    ▶ [EVENTS] 088 Starting handler, subscriber_name=task.deleted.task.counter.decrease, topic=task.deleted
2022-03-20T15:13:17.339977937Z: INFO    ▶ [EVENTS] 089 Starting handler, subscriber_name=task.deleted.task.deleted.notification.send, topic=task.deleted
2022-03-20T15:13:17.340216841Z: INFO    ▶ [EVENTS] 08c Starting handler, subscriber_name=task.assignee.created.task.assignee.subscribe, topic=task.assignee.created
2022-03-20T15:13:17.339122784Z: INFO    ▶ [EVENTS] 07d Starting handler, subscriber_name=task.updated.task.updated.mentions, topic=task.updated
2022-03-20T15:13:17.33948113Z: INFO     ▶ [EVENTS] 080 Starting handler, subscriber_name=list.created.list.counter.increase, topic=list.created
2022-03-20T15:13:17.340178971Z: INFO    ▶ [EVENTS] 08b Starting handler, subscriber_name=task.created.task.created.mentions, topic=task.created
YES, I CONFIRM
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xca3774]

goroutine 1 [running]:
code.vikunja.io/api/pkg/user.(*User).GetName(...)
        /go/src/code.vikunja.io/api/pkg/user/user.go:144
code.vikunja.io/api/pkg/user.(*AccountDeletedNotification).ToMail(0x4000296010, 0x119de18)
        /go/src/code.vikunja.io/api/pkg/user/notifications.go:259 +0x54
code.vikunja.io/api/pkg/notifications.notifyMail(0x14dee68, 0x400015f0e0, 0x14e6f78, 0x4000296010, 0x400050f938, 0xcf15e8)
        /go/src/code.vikunja.io/api/pkg/notifications/notification.go:65 +0x30
code.vikunja.io/api/pkg/notifications.Notify(0x14dee68, 0x400015f0e0, 0x14e6f78, 0x4000296010, 0x0, 0x0)
        /go/src/code.vikunja.io/api/pkg/notifications/notification.go:56 +0x144
code.vikunja.io/api/pkg/models.DeleteUser(0x4000107450, 0x400015f0e0, 0x1, 0x400015f0e0)
        /go/src/code.vikunja.io/api/pkg/models/user_delete.go:170 +0x684
code.vikunja.io/api/pkg/cmd.glob..func24(0x1b86620, 0x4000456860, 0x1, 0x2)
        /go/src/code.vikunja.io/api/pkg/cmd/user.go:342 +0x158
github.com/spf13/cobra.(*Command).execute(0x1b86620, 0x4000456840, 0x2, 0x2, 0x1b86620, 0x4000456840)
        /go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x1d0
github.com/spf13/cobra.(*Command).ExecuteC(0x1b86da0, 0x40d1fc, 0x4000000180, 0x4000044800)
        /go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x274
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
code.vikunja.io/api/pkg/cmd.Execute()
        /go/src/code.vikunja.io/api/pkg/cmd/cmd.go:44 +0x30
main.main()
        /go/src/code.vikunja.io/api/main.go:22 +0x20
```

Probably also imporant to mention here, is that both my regular (non Oauth) user on Vikunja, and the added Oauth accounts have the exact same email address linked to it.

**Comment by kolaente** [comment]
What version are you using? Can you reproduce this with the latest unstable?

**Comment by RoboMagus** [comment]
Wow, great response time!!
I'm currently on `Vikunja api version v0.18.1`. Not sure how to find the docker image version though.
I'll quickly try to pull unstable and get back to you after I try to reproduce it.

**Comment by RoboMagus** [comment]
Yes, on the `unstable` version, I can now delete these users from commandline.
However, when trying to login now using Authentik, as I used to before, I now get an error page: 
```
Redirect URI Error
The request fails due to a missing, invalid, or mismatching redirection URI (redirect_uri).
```

Related to this: Can vikunja be made to grab e.g. the `preferred_username`, `name`, `nickname`, or anything similar from the open-id scopes instead of creating a random username?
And would it be possible to migrate all data from an existing local user to a user created by logging in using openid?

**Comment by kolaente** [comment]
> However, when trying to login now using Authentik, as I used to before, I now get an error page:

Did you upgrade to the unstable frontend as well?

> Related to this: Can vikunja be made to grab e.g. the preferred_username, name, nickname, or anything similar from the open-id scopes instead of creating a random username?

This should already be the case, but sometimes the names are not exposed correctly. I'm sure it works with gitlab as that's what I tested it with but I'm not sure about other providers. The usernames have to be unique across all providers so if you already have a user from another source with the same username it will fallback to generating a random one.

> And would it be possible to migrate all data from an existing local user to a user created by logging in using openid?

You could, but there's no real supported migration path or similar. You would need to manually delete the local user in the DB (not with the cli command because that would remove all user data as well) and then change the id of the other user to the one of the deleted local user. Make a backup before trying this.

**Comment by RoboMagus** [comment]
I see there was a problem on my part. A typo in the allowed authentication redirect url...


> This should already be the case, but sometimes the names are not exposed correctly. I'm sure it works with gitlab as that's what I tested it with but I'm not sure about other providers. The usernames have to be unique across all providers so if you already have a user from another source with the same username it will fallback to generating a random one.

And that would clarify why I'm getting randomized usernames when trying to login using Authentik; I'm using the same prefered username as what I already have configured in Vikunja's local users. Oops 🥲 

I'll use your suggestion to migrate my data from one account to the other. Thanks!
