### ISSUE TITLE
Internal Server Error: Status 500 - panic: gob: registering duplicate names

### ISSUE THREAD

**Issue by alexdelprete** [go-vikunja/api#66]
### Description

Vikunja docker install was pretty straightforward, but I noticed while using the frontend that I had an internal server error 500 red box randomly.

I checked the log of the API container and found some strange "registering duplicate names" errors and I think they cause the HTTP error 500.

```log
⇨ http server started on [::]:3456
2023-01-31T15:53:04.692152215+01:00: WEB 	▶ 172.19.0.1  GET 200 /api/v1/info 297.269µs - Uptime-Kuma/1.19.6
panic: gob: registering duplicate names for *models.Task: "code.vikunja.io/api/pkg/models.Task" != "*models.Task"
goroutine 211 [running]:
encoding/gob.RegisterName({0x11e775f, 0xc}, {0x13cbd20, 0xc0005ac200})
	/usr/local/go/src/encoding/gob/type.go:826 +0x339
encoding/gob.Register({0x13cbd20, 0xc0005ac200})
	/usr/local/go/src/encoding/gob/type.go:874 +0x1ba
xorm.io/xorm/tags.(*Parser).ParseWithCache(0xc000456200, {0x13cbd20?, 0xc0005ac200?, 0xc0004aee70?})
	/go/pkg/mod/xorm.io/xorm@v1.3.2/tags/parser.go:104 +0x178
xorm.io/xorm.(*Session).noCacheFind(0xc0004449c0, 0xc0005ba3c0, {0x124c500?, 0xc000516348?, 0xa316dc?}, {0xc000446200, 0x102}, {0xc0004aee70, 0x1, 0x1})
	/go/pkg/mod/xorm.io/xorm@v1.3.2/session_find.go:237 +0x5a8
xorm.io/xorm.(*Session).find(0xc0004449c0, {0x12335c0?, 0xc000516348?}, {0x0, 0x0, 0xc0004aed70?})
	/go/pkg/mod/xorm.io/xorm@v1.3.2/session_find.go:161 +0x9ff
xorm.io/xorm.(*Session).Find(0xc0005c8b40?, {0x12335c0?, 0xc000516348?}, {0x0?, 0x0?, 0x0?})
	/go/pkg/mod/xorm.io/xorm@v1.3.2/session_find.go:31 +0x7b
code.vikunja.io/api/pkg/models.getUndoneOverdueTasks(0xc0004449c0, {0x4687a9?, 0xc00001782d?, 0x2221080?})
	/go/src/code.vikunja.io/api/pkg/models/task_overdue_reminder.go:44 +0x245
code.vikunja.io/api/pkg/models.RegisterOverdueReminderCron.func1()
	/go/src/code.vikunja.io/api/pkg/models/task_overdue_reminder.go:128 +0x9c
github.com/robfig/cron/v3.FuncJob.Run(0xc0005a4320?)
	/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:136 +0x1a
github.com/robfig/cron/v3.(*Cron).startJob.func1()
	/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:312 +0x6a
created by github.com/robfig/cron/v3.(*Cron).startJob
	/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:310 +0xad
usermod: no changes
2023/01/31 15:54:00 Using config file: /etc/vikunja/config.yml
2023/01/31 15:54:00 Redis initialized
2023-01-31T15:54:00.743090919+01:00: INFO	▶ migration/Migrate 04f Ran all migrations successfully.
2023-01-31T15:54:00.743449317+01:00: INFO	▶ cmd/func25 051 Vikunja version v0.20.2
2023-01-31T15:54:00.744160982+01:00: INFO	▶ [EVENTS] 055 Adding handler, handler_name=poison.logger, topic=poison
2023-01-31T15:54:00.744195262+01:00: INFO	▶ [EVENTS] 057 Adding handler, handler_name=team.created.team.counter.increase, topic=team.created
2023-01-31T15:54:00.744208168+01:00: INFO	▶ [EVENTS] 058 Adding handler, handler_name=task.comment.edited.handle.task.comment.edit.mentions, topic=task.comment.edited
2023-01-31T15:54:00.744224818+01:00: INFO	▶ [EVENTS] 059 Adding handler, handler_name=user.export.requested.handle.user.data.export, topic=user.export.requested
2023-01-31T15:54:00.744241888+01:00: INFO	▶ [EVENTS] 05a Adding handler, handler_name=user.created.increase.user.counter, topic=user.created
2023-01-31T15:54:00.744256913+01:00: INFO	▶ [EVENTS] 05b Adding handler, handler_name=namespace.deleted.namespace.counter.decrease, topic=namespace.deleted
2023-01-31T15:54:00.74427486+01:00: INFO	▶ [EVENTS] 05c Adding handler, handler_name=task.deleted.task.counter.decrease, topic=task.deleted
2023-01-31T15:54:00.744289463+01:00: INFO	▶ [EVENTS] 05d Adding handler, topic=task.deleted, handler_name=task.deleted.task.deleted.notification.send
2023-01-31T15:54:00.744299358+01:00: INFO	▶ [EVENTS] 05e Adding handler, handler_name=namespace.created.namespace.counter.increase, topic=namespace.created
2023-01-31T15:54:00.744309617+01:00: INFO	▶ [EVENTS] 05f Adding handler, handler_name=task.assignee.created.task.assigned.notification.send, topic=task.assignee.created
2023-01-31T15:54:00.744318726+01:00: INFO	▶ [EVENTS] 060 Adding handler, handler_name=task.assignee.created.task.assignee.subscribe, topic=task.assignee.created
2023-01-31T15:54:00.744327952+01:00: INFO	▶ [EVENTS] 061 Adding handler, handler_name=list.created.list.counter.increase, topic=list.created
2023-01-31T15:54:00.744336927+01:00: INFO	▶ [EVENTS] 062 Adding handler, handler_name=list.created.send.list.created.notification, topic=list.created
2023-01-31T15:54:00.74434548+01:00: INFO	▶ [EVENTS] 063 Adding handler, handler_name=task.created.task.counter.increase, topic=task.created
2023-01-31T15:54:00.744364057+01:00: INFO	▶ [EVENTS] 064 Adding handler, handler_name=task.created.task.created.mentions, topic=task.created
2023-01-31T15:54:00.744374641+01:00: INFO	▶ [EVENTS] 065 Adding handler, handler_name=task.comment.created.task.comment.notification.send, topic=task.comment.created
2023-01-31T15:54:00.744387921+01:00: INFO	▶ [EVENTS] 066 Adding handler, topic=team.member.added, handler_name=team.member.added.team.member.added.notification
2023-01-31T15:54:00.744396407+01:00: INFO	▶ [EVENTS] 067 Adding handler, topic=task.updated, handler_name=task.updated.task.updated.mentions
2023-01-31T15:54:00.744408753+01:00: INFO	▶ [EVENTS] 068 Adding handler, handler_name=list.deleted.list.counter.decrease, topic=list.deleted
2023-01-31T15:54:00.744418169+01:00: INFO	▶ [EVENTS] 069 Adding handler, handler_name=team.deleted.team.counter.decrease, topic=team.deleted
2023-01-31T15:54:00.745507698+01:00: INFO	▶ [EVENTS] 082 Starting handler, subscriber_name=list.created.list.counter.increase, topic=list.created
2023-01-31T15:54:00.745507696+01:00: INFO	▶ [EVENTS] 081 Starting handler, subscriber_name=task.comment.created.task.comment.notification.send, topic=task.comment.created
2023-01-31T15:54:00.745535748+01:00: INFO	▶ [EVENTS] 083 Starting handler, subscriber_name=list.deleted.list.counter.decrease, topic=list.deleted
2023-01-31T15:54:00.745582743+01:00: INFO	▶ [EVENTS] 085 Starting handler, subscriber_name=user.created.increase.user.counter, topic=user.created
2023-01-31T15:54:00.745597018+01:00: INFO	▶ [EVENTS] 087 Starting handler, subscriber_name=task.comment.edited.handle.task.comment.edit.mentions, topic=task.comment.edited
2023-01-31T15:54:00.745603307+01:00: INFO	▶ [EVENTS] 088 Starting handler, subscriber_name=task.deleted.task.counter.decrease, topic=task.deleted
2023-01-31T15:54:00.74561158+01:00: INFO	▶ [EVENTS] 089 Starting handler, subscriber_name=namespace.deleted.namespace.counter.decrease, topic=namespace.deleted
2023-01-31T15:54:00.745617806+01:00: INFO	▶ [EVENTS] 08a Starting handler, subscriber_name=task.deleted.task.deleted.notification.send, topic=task.deleted
2023-01-31T15:54:00.745625606+01:00: INFO	▶ [EVENTS] 08b Starting handler, subscriber_name=list.created.send.list.created.notification, topic=list.created
2023-01-31T15:54:00.745641+01:00: INFO	▶ [EVENTS] 08c Starting handler, subscriber_name=task.updated.task.updated.mentions, topic=task.updated
2023-01-31T15:54:00.745850517+01:00: INFO	▶ [EVENTS] 08d Starting handler, subscriber_name=team.deleted.team.counter.decrease, topic=team.deleted
2023-01-31T15:54:00.745895422+01:00: INFO	▶ [EVENTS] 08e Starting handler, subscriber_name=task.created.task.counter.increase, topic=task.created
2023-01-31T15:54:00.74591482+01:00: INFO	▶ [EVENTS] 08f Starting handler, subscriber_name=namespace.created.namespace.counter.increase, topic=namespace.created
2023-01-31T15:54:00.745584798+01:00: INFO	▶ [EVENTS] 086 Starting handler, subscriber_name=team.created.team.counter.increase, topic=team.created
2023-01-31T15:54:00.746151348+01:00: INFO	▶ [EVENTS] 090 Starting handler, topic=poison, subscriber_name=poison.logger
2023-01-31T15:54:00.74628031+01:00: INFO	▶ [EVENTS] 091 Starting handler, subscriber_name=task.created.task.created.mentions, topic=task.created
2023-01-31T15:54:00.746359225+01:00: INFO	▶ [EVENTS] 092 Starting handler, subscriber_name=team.member.added.team.member.added.notification, topic=team.member.added
2023-01-31T15:54:00.745535762+01:00: INFO	▶ [EVENTS] 084 Starting handler, subscriber_name=task.assignee.created.task.assigned.notification.send, topic=task.assignee.created
2023-01-31T15:54:00.746463108+01:00: INFO	▶ [EVENTS] 093 Starting handler, subscriber_name=task.assignee.created.task.assignee.subscribe, topic=task.assignee.created
2023-01-31T15:54:00.746546425+01:00: INFO	▶ [EVENTS] 094 Starting handler, subscriber_name=user.export.requested.handle.user.data.export, topic=user.export.requested
⇨ http server started on [::]:3456
2023-01-31T15:54:04.745292697+01:00: WEB 	▶ 172.19.0.1  GET 200 /api/v1/info 253.612µs - Uptime-Kuma/1.19.6
2023-01-31T15:54:14.421232193+01:00: WEB 	▶ 10.1.10.45  GET 200 /api/v1/notifications?page=1 10.032809ms - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.0.0
2023-01-31T15:54:15.037169512+01:00: WEB 	▶ 10.1.10.45  GET 200 /api/v1/notifications?page=1 3.011396ms - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.0.0
2023-01-31T15:54:17.661250044+01:00: WEB 	▶ 10.1.10.45  GET 200 /api/v1/info 102.931µs - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.0.0
2023-01-31T15:54:17.921537399+01:00: WEB 	▶ 10.1.10.45  GET 200 /api/v1/user 2.550446ms - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.0.0
2023-01-31T15:54:18.180224994+01:00: WEB 	▶ 10.1.10.45  GET 200 /api/v1/labels?page=1 7.58247ms - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.0.0
2023-01-31T15:54:18.181690847+01:00: WEB 	▶ 10.1.10.45  GET 200 /api/v1/notifications?page=1 4.313852ms - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.0.0
2023-01-31T15:54:18.185200567+01:00: - 	▶ echo recover.go:113 [PANIC RECOVER] gob: registering duplicate names for *models.List: "code.vikunja.io/api/pkg/models.List" != "*models.List" goroutine 237 [running]:
github.com/labstack/echo/v4/middleware.RecoverWithConfig.func1.1.1()
	/go/pkg/mod/github.com/labstack/echo/v4@v4.10.0/middleware/recover.go:93 +0x14e
panic({0x126b4c0, 0xc000413f10})
	/usr/local/go/src/runtime/panic.go:884 +0x212
encoding/gob.RegisterName({0x11e7751, 0xc}, {0x13b3a60, 0xc0000b4d00})
	/usr/local/go/src/encoding/gob/type.go:826 +0x339
encoding/gob.Register({0x13b3a60, 0xc0000b4d00})
	/usr/local/go/src/encoding/gob/type.go:874 +0x1ba
xorm.io/xorm/tags.(*Parser).ParseWithCache(0xc00046c200, {0x13b3a60?, 0xc0000b4d00?, 0xc000024500?})
	/go/pkg/mod/xorm.io/xorm@v1.3.2/tags/parser.go:104 +0x178
xorm.io/xorm.(*Session).noCacheFind(0xc000526c30, 0xc0002db770, {0x124c2c0?, 0xc0000eef78?, 0x2?}, {0xc000712000, 0x239}, {0xc000024500, 0x8, 0x8})
	/go/pkg/mod/xorm.io/xorm@v1.3.2/session_find.go:237 +0x5a8
xorm.io/xorm.(*Session).find(0xc000526c30, {0x1233400?, 0xc0000eef78?}, {0x0, 0x0, 0x0?})
	/go/pkg/mod/xorm.io/xorm@v1.3.2/session_find.go:161 +0x9ff
xorm.io/xorm.(*Session).Find(0xc000409200?, {0x1233400?, 0xc0000eef78?}, {0x0?, 0x5?, 0x24?})
	/go/pkg/mod/xorm.io/xorm@v1.3.2/session_find.go:31 +0x7b
code.vikunja.io/api/pkg/models.getRawListsForUser(0xc000526c30, 0xc00058d190)
	/go/src/code.vikunja.io/api/pkg/models/list.go:427 +0x51c
code.vikunja.io/api/pkg/models.(*TaskCollection).ReadAll(0xc000552160, 0x14180e0?, {0x17c6120, 0xc0005522c0?}, {0x0, 0x0}, 0x1, 0x32)
	/go/src/code.vikunja.io/api/pkg/models/task_collection.go:182 +0x325
code.vikunja.io/web/handler.(*WebHandler).ReadAllWeb(0x103915f?, {0x17e3c70, 0xc0001c4780})
	/go/pkg/mod/code.vikunja.io/web@v0.0.0-20210706160506-d85def955bd3/handler/read_all.go:94 +0x531
code.vikunja.io/api/pkg/routes.setupMetricsMiddleware.func1.1({0x17e3c70, 0xc0001c4780})
	/go/src/code.vikunja.io/api/pkg/routes/metrics.go:105 +0xdb
github.com/labstack/echo-jwt/v4.Config.ToMiddleware.func2.1({0x17e3c70, 0xc0001c4780})
	/go/pkg/mod/github.com/labstack/echo-jwt/v4@v4.0.1/jwt.go:223 +0x3fe
code.vikunja.io/api/pkg/routes.registerAPIRoutes.func1.1({0x17e3c70, 0xc0001c4780})
	/go/src/code.vikunja.io/api/pkg/routes/routes.go:225 +0xef
github.com/labstack/echo/v4.(*Echo).add.func1({0x17e3c70, 0xc0001c4780})
	/go/pkg/mod/github.com/labstack/echo/v4@v4.10.0/echo.go:546 +0x51
github.com/labstack/echo/v4/middleware.CORSWithConfig.func1.1({0x17e3c70, 0xc0001c4780})
	/go/pkg/mod/github.com/labstack/echo/v4@v4.10.0/middleware/cors.go:190 +0x47e
github.com/labstack/echo/v4/middleware.RecoverWithConfig.func1.1({0x17e3c70, 0xc0001c4780})
	/go/pkg/mod/github.com/labstack/echo/v4@v4.10.0/middleware/recover.go:119 +0xfe
github.com/labstack/echo/v4/middleware.LoggerWithConfig.func2.1({0x17e3c70, 0xc0001c4780})
	/go/pkg/mod/github.com/labstack/echo/v4@v4.10.0/middleware/logger.go:126 +0xe2
github.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc00002ad80, {0x17cffa8?, 0xc000366460}, 0xc000535500)
	/go/pkg/mod/github.com/labstack/echo/v4@v4.10.0/echo.go:633 +0x3d1
net/http.serverHandler.ServeHTTP({0xc0005464b0?}, {0x17cffa8, 0xc000366460}, 0xc000535500)
	/usr/local/go/src/net/http/server.go:2947 +0x30c
net/http.(*conn).serve(0xc0001c4640, {0x17d0b68, 0xc0003d0210})
	/usr/local/go/src/net/http/server.go:1991 +0x607
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3102 +0x4db
goroutine 1 [chan receive]:
code.vikunja.io/api/pkg/cmd.glob..func25(0x216d4a0?, {0x141aa23?, 0x0?, 0x0?})
	/go/src/code.vikunja.io/api/pkg/cmd/web.go:102 +0x19e
github.com/spf13/cobra.(*Command).execute(0x216d4a0, {0xc000040220, 0x0, 0x0})
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x216d4a0)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
code.vikunja.io/api/pkg/cmd.Execute()
	/go/src/code.vikunja.io/api/pkg/cmd/cmd.go:44 +0x25
main.main()
	/go/src/code.vikunja.io/api/main.go:22 +0x17
goroutine 8 [select]:
github.com/go-redis/redis/v8/internal/pool.(*ConnPool).reaper(0xc0000b1220, 0x0?)
	/go/pkg/mod/githu
2023-01-31T15:54:18.185236584+01:00: WEB 	▶ 10.1.10.45  GET 500 /api/v1/tasks/all?sort_by[]=due_date&sort_by[]=id&order_by[]=asc&order_by[]=desc&filter_by[]=done&filter_by[]=due_date&filter_by[]=due_date&filter_value[]=false&filter_value[]=2023-02-07T14:54:19.595Z&filter_value[]=2023-01-31T14:54:19.595Z&filter_comparator[]=equals&filter_comparator[]=less&filter_comparator[]=greater&filter_concat=and&filter_include_nulls=false&page=1 7.899602ms - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.0.0
2023-01-31T15:54:18.195685433+01:00: WEB 	▶ 10.1.10.45  GET 200 /api/v1/namespaces?is_archived=true&page=1 23.109421ms - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.0.0
2023-01-31T15:54:18.21938883+01:00: WEB 	▶ 10.1.10.45  GET 200 /api/v1/avatar/alexdelprete?size=50&=1675176859539 54.5415ms - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.0.0
```

### Vikunja Frontend Version

0.20.3

### Vikunja API Version

0.20.2

### Browser and version

Edge 111.0.1633.0

### Can you reproduce the bug on the Vikunja demo site?

No

**Comment by kolaente** [comment]
Are you using caches?

**Comment by alexdelprete** [comment]
> Are you using caches?

redis

**Comment by kolaente** [comment]
Try disabling it.

**Comment by kolaente** [comment]
You can leave it disabled.

If you don't have Vikunja set up with a HA setup where it load balances over multiple running instances, using memory instead of redis is usually faster.

**Comment by kolaente** [comment]
Going to close this as it can be solved with a configuration change right now and we'll change the caching behaviour in the future anyway.

**Comment by verymilan** [comment]
> using memory instead of redis is usually faster.

However it looks like also that option causes this error on each initial list load right after restarting Vikunja. So indeed the only option appears to be to entirely disabling the cache. Perhaps there should be a (clear) warning in the docs or something like that... because of course i jump to configuring such a cache if i intend to set my application up correctly. Not suggesting that in case of Vikunja its incorrect, but just in terms of ...instinct. :)
